//autogenerated:yes
//nolint:revive,misspell,govet,lll,dupl,gocritic
package magothy

import (
	"strconv"
	"strings"
	"fmt"
)
// Flags for gimbal device (lower level) operation.
type GIMBAL_DEVICE_FLAGS uint64

const (
	// Set to retracted safe position (no stabilization), takes presedence over all other flags.
	GIMBAL_DEVICE_FLAGS_RETRACT GIMBAL_DEVICE_FLAGS = 1
	// Set to neutral position (horizontal, forward looking, with stabiliziation), takes presedence over all other flags except RETRACT.
	GIMBAL_DEVICE_FLAGS_NEUTRAL GIMBAL_DEVICE_FLAGS = 2
	// Lock roll angle to absolute angle relative to horizon (not relative to drone). This is generally the default with a stabilizing gimbal.
	GIMBAL_DEVICE_FLAGS_ROLL_LOCK GIMBAL_DEVICE_FLAGS = 4
	// Lock pitch angle to absolute angle relative to horizon (not relative to drone). This is generally the default.
	GIMBAL_DEVICE_FLAGS_PITCH_LOCK GIMBAL_DEVICE_FLAGS = 8
	// Lock yaw angle to absolute angle relative to North (not relative to drone). If this flag is set, the quaternion is in the Earth frame with the x-axis pointing North (yaw absolute). If this flag is not set, the quaternion frame is in the Earth frame rotated so that the x-axis is pointing forward (yaw relative to vehicle).
	GIMBAL_DEVICE_FLAGS_YAW_LOCK GIMBAL_DEVICE_FLAGS = 16
)

var labels_GIMBAL_DEVICE_FLAGS = map[GIMBAL_DEVICE_FLAGS]string{
	GIMBAL_DEVICE_FLAGS_RETRACT: "GIMBAL_DEVICE_FLAGS_RETRACT",
	GIMBAL_DEVICE_FLAGS_NEUTRAL: "GIMBAL_DEVICE_FLAGS_NEUTRAL",
	GIMBAL_DEVICE_FLAGS_ROLL_LOCK: "GIMBAL_DEVICE_FLAGS_ROLL_LOCK",
	GIMBAL_DEVICE_FLAGS_PITCH_LOCK: "GIMBAL_DEVICE_FLAGS_PITCH_LOCK",
	GIMBAL_DEVICE_FLAGS_YAW_LOCK: "GIMBAL_DEVICE_FLAGS_YAW_LOCK",
}

var values_GIMBAL_DEVICE_FLAGS = map[string]GIMBAL_DEVICE_FLAGS{
	"GIMBAL_DEVICE_FLAGS_RETRACT": GIMBAL_DEVICE_FLAGS_RETRACT,
	"GIMBAL_DEVICE_FLAGS_NEUTRAL": GIMBAL_DEVICE_FLAGS_NEUTRAL,
	"GIMBAL_DEVICE_FLAGS_ROLL_LOCK": GIMBAL_DEVICE_FLAGS_ROLL_LOCK,
	"GIMBAL_DEVICE_FLAGS_PITCH_LOCK": GIMBAL_DEVICE_FLAGS_PITCH_LOCK,
	"GIMBAL_DEVICE_FLAGS_YAW_LOCK": GIMBAL_DEVICE_FLAGS_YAW_LOCK,
}

// MarshalText implements the encoding.TextMarshaler interface.
func (e GIMBAL_DEVICE_FLAGS) MarshalText() ([]byte, error) {
	if e == 0 {
		return []byte("0"), nil
	}
	var names []string
	for i := 0; i < 5; i++ {
		mask := GIMBAL_DEVICE_FLAGS(1 << i)
		if e&mask == mask {
			names = append(names, labels_GIMBAL_DEVICE_FLAGS[mask])
		}
	}
	return []byte(strings.Join(names, " | ")), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface.
func (e *GIMBAL_DEVICE_FLAGS) UnmarshalText(text []byte) error {
	labels := strings.Split(string(text), " | ")
	var mask GIMBAL_DEVICE_FLAGS
	for _, label := range labels {
		if value, ok := values_GIMBAL_DEVICE_FLAGS[label]; ok {
			mask |= value
		} else if value, err := strconv.Atoi(label); err == nil {
			mask |= GIMBAL_DEVICE_FLAGS(value)
		} else {
			return fmt.Errorf("invalid label '%s'", label)
		}
	}
	*e = mask
	return nil
}

// String implements the fmt.Stringer interface.
func (e GIMBAL_DEVICE_FLAGS) String() string {
	val, _ := e.MarshalText()
	return string(val)
}
