//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Request that the vehicle report terrain height at the given location. Used by GCS to check if vehicle has all terrain data needed for a mission.
type MessageTerrainCheck struct {
	// Latitude
	Lat int32
	// Longitude
	Lon int32
}

// GetID implements the message.Message interface.
func (*MessageTerrainCheck) GetID() uint32 {
	return 135
}
