//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Sent from Vehicle to Magothy Console. Sent as a response to MAGOTHY_MISSION_TRANSFER
type MessageMagothyMissionAck struct {
	// system id of target system
	TargetSystem uint8
	// increment at the beginning of each "session", can be used to correlate different chunks or detect new sessions
	SessionId uint8
	// chunk index
	ChunkIndex uint8
	// total number of chunks
	NumChunk uint8
	// CRC-16/CCITT-FALSE of complete payload
	Crc16 uint16
	// result of command
	Result MAV_MISSION_RESULT `mavenum:"uint8"`
}

// GetID implements the message.Message interface.
func (*MessageMagothyMissionAck) GetID() uint32 {
	return 50252
}
