//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Report beacon detection
type MessageMagothyBeaconDetection struct {
	// beacon id of detection
	BeaconId uint8
	// 12-bit bitmask, 30 deg increments, bit 0 == 0deg, bit 1 == 30deg, ...
	PositionMask uint16
	// Latitude (deg)
	LatDeg float32
	// Longitude (deg)
	LonDeg float32
	// Speed (m/s)
	SpeedMps float32
	// Course (deg)
	CourseDeg float32
	// Estimated Position Error (m)
	ErrorM float32
}

// GetID implements the message.Message interface.
func (*MessageMagothyBeaconDetection) GetID() uint32 {
	return 50006
}
