//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Report Magothy specific capabilities
type MessageMagothyCapability struct {
	// Additional Capability Bitmask
	EnablementBitmask MAGOTHY_CAPABILITY `mavenum:"uint16"`
	// IP Address to Spy server
	SpyIpAddress [4]uint8
	// Port to Spy server
	SpyPort uint16
	// IP Address to Log WebDAV server
	LogManagementIpAddress [4]uint8
	// Port to Log WebDAV server
	LogManagementPort uint16
	// Base URL prefix to Log WebDAV server
	LogManagementEndpoint string `mavlen:"32"`
	// IP Address to Firmware Update web server
	FirmwareUploadIpAddress [4]uint8
	// Port to Firmware Update web server
	FirmwareUploadPort uint16
	// Base URL prefix to Firmware Update web server
	FirmwareUploadEndpoint string `mavlen:"32"`
	// sha1 of meta-magothy
	FirmwareSha1 [20]uint8
	// sha1 is clean if 0, else dirty
	FirmwareSha1Dirty uint8
	// Pretty version string
	FirmwareVersion string `mavlen:"32"`
	// Identifier to distinguish between vehicle types
	DeviceType string `mavlen:"16"`
	// Log file date time prefix
	LogDateTime string `mavlen:"20"`
	// Vehicle Name - Log file suffix
	VehicleName string `mavlen:"16"`
}

// GetID implements the message.Message interface.
func (*MessageMagothyCapability) GetID() uint32 {
	return 50100
}
