//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Sent to/from Magothy Console and Vehicle. Encapsulates a serialized protobuf message
type MessageMagothyProtobufProxy struct {
	// Message ID to corresponding to protobuf message type
	ProtoId uint16
	// 0 - not compressed, 1 - compressed with zstd
	IsCompressed uint8
	// length of serialized protobuf message
	DataLen uint8
	// serialized protobuf message buffer
	Data [251]uint8
}

// GetID implements the message.Message interface.
func (*MessageMagothyProtobufProxy) GetID() uint32 {
	return 50005
}
