//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Sent to/from Magothy Console and Vehicle. Used to transfer a portion of a large payload. When the Vehicle receives this message, it will respond with MAGOTHY_LICENSE_TRANSFER_ACK
type MessageMagothyLicenseTransfer struct {
	// system id of target system
	TargetSystem uint8
	// file type
	TransferType MAGOTHY_LICENSE_TRANSFER_TYPE `mavenum:"uint8"`
	// chunk index
	ChunkIndex uint8
	// total number of chunks
	NumChunk uint8
	// CRC-16/CCITT-FALSE of complete payload
	Crc16 uint16
	// length of this chunk payload
	PayloadLen uint8
	// payload of this chunk
	Payload [248]uint8
}

// GetID implements the message.Message interface.
func (*MessageMagothyLicenseTransfer) GetID() uint32 {
	return 50154
}
