//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Sent from Magothy Console to Vehicle, command to generate an license [de]activation file. Vehicle will respond with MAGOTHY_LICENSE_TRANSFER_ACK
type MessageMagothyLicenseTransferInitialize struct {
	// system id of target system
	TargetSystem uint8
	// file type
	TransferType MAGOTHY_LICENSE_TRANSFER_TYPE `mavenum:"uint8"`
	// license product_key - must be null terminated if length is less than 64
	ProductKey string `mavlen:"64"`
	// user provided description - must be null terminated if length is less than 64
	Description string `mavlen:"64"`
}

// GetID implements the message.Message interface.
func (*MessageMagothyLicenseTransferInitialize) GetID() uint32 {
	return 50151
}
