//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Sent from Vehicle. Contains product licensing information such as product key and activation status.
type MessageMagothyLicenseInfo struct {
	// 1 if license key is set, else 0
	IsSet uint8
	// 1 if license key is valid, else 0
	IsValid uint8
	// license product_key - must be null terminated if length is less than 64
	ProductKey string `mavlen:"64"`
	// user provided description - must be null terminated if length is less than 64
	Description string `mavlen:"64"`
}

// GetID implements the message.Message interface.
func (*MessageMagothyLicenseInfo) GetID() uint32 {
	return 50150
}
