//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// The RAW values of the RC channels sent to the MAV to override info received from the RC radio. A value of UINT16_MAX means no change to that channel. A value of 0 means control of that channel should be released back to the RC radio. The standard PPM modulation is as follows: 1000 microseconds: 0%, 2000 microseconds: 100%. Individual receivers/transmitters might violate this specification.
type MessageRcChannelsOverride struct {
	// System ID
	TargetSystem uint8
	// Component ID
	TargetComponent uint8
	// RC channel 1 value. A value of UINT16_MAX means to ignore this field.
	Chan1Raw uint16
	// RC channel 2 value. A value of UINT16_MAX means to ignore this field.
	Chan2Raw uint16
	// RC channel 3 value. A value of UINT16_MAX means to ignore this field.
	Chan3Raw uint16
	// RC channel 4 value. A value of UINT16_MAX means to ignore this field.
	Chan4Raw uint16
	// RC channel 5 value. A value of UINT16_MAX means to ignore this field.
	Chan5Raw uint16
	// RC channel 6 value. A value of UINT16_MAX means to ignore this field.
	Chan6Raw uint16
	// RC channel 7 value. A value of UINT16_MAX means to ignore this field.
	Chan7Raw uint16
	// RC channel 8 value. A value of UINT16_MAX means to ignore this field.
	Chan8Raw uint16
	// RC channel 9 value. A value of 0 or UINT16_MAX means to ignore this field.
	Chan9Raw uint16 `mavext:"true"`
	// RC channel 10 value. A value of 0 or UINT16_MAX means to ignore this field.
	Chan10Raw uint16 `mavext:"true"`
	// RC channel 11 value. A value of 0 or UINT16_MAX means to ignore this field.
	Chan11Raw uint16 `mavext:"true"`
	// RC channel 12 value. A value of 0 or UINT16_MAX means to ignore this field.
	Chan12Raw uint16 `mavext:"true"`
	// RC channel 13 value. A value of 0 or UINT16_MAX means to ignore this field.
	Chan13Raw uint16 `mavext:"true"`
	// RC channel 14 value. A value of 0 or UINT16_MAX means to ignore this field.
	Chan14Raw uint16 `mavext:"true"`
	// RC channel 15 value. A value of 0 or UINT16_MAX means to ignore this field.
	Chan15Raw uint16 `mavext:"true"`
	// RC channel 16 value. A value of 0 or UINT16_MAX means to ignore this field.
	Chan16Raw uint16 `mavext:"true"`
	// RC channel 17 value. A value of 0 or UINT16_MAX means to ignore this field.
	Chan17Raw uint16 `mavext:"true"`
	// RC channel 18 value. A value of 0 or UINT16_MAX means to ignore this field.
	Chan18Raw uint16 `mavext:"true"`
}

// GetID implements the message.Message interface.
func (*MessageRcChannelsOverride) GetID() uint32 {
	return 70
}
