//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Reports depth and temperature measured by echosounder
type MessageMagothyEchosounder struct {
	// Timestamp (UNIX Epoch time or time since system boot). The receiving end can infer timestamp format (since 1.1.1970 or since system boot) by checking for the magnitude of the number.
	TimeUsec uint64
	// Water Depth (Low Frequency) (m)
	WaterDepthLowFreqM float32
	// Water Depth (High Frequency) (m)
	WaterDepthHighFreqM float32
	// Water Temperature (C)
	WaterTemperatureC float32 `mavname:"water_temperature_C"`
}

// GetID implements the message.Message interface.
func (*MessageMagothyEchosounder) GetID() uint32 {
	return 50001
}
