//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Sent from Magothy Console to Vehicle, requests a chunk of the loaded mission. Vehicle will respond with MAGOTHY_MISSION_TRANSFER
type MessageMagothyMissionRequest struct {
	// system id of target system
	TargetSystem uint8
	// increment at the beginning of each "session", can be used to correlate different chunks or detect new sessions
	SessionId uint8
	// chunk index of license transfer
	ChunkIndex uint8
}

// GetID implements the message.Message interface.
func (*MessageMagothyMissionRequest) GetID() uint32 {
	return 50250
}
