//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Report mission based telemetry
type MessageMagothyMissionTelemetry struct {
	// Unix Timestamp
	UnixTimeUsec uint64
	// Vehicle Controller uptime
	UptimeMsec uint32
	// Elasped time of currently executing mission item (s) - NaN if not in mission
	MissionItemTimeElapsedS float32
	// Remaining time of currently executing mission item (s) - NaN if not in mission
	MissionItemTimeRemainingS float32
	// Elasped time of entire mission (s) - NaN if not in mission
	MissionTimeElapsedS float32
	// Remaining time of entire mission (s) - NaN if not in mission
	MissionTimeRemainingS float32
	// Distance to target (waypoint/loiter/etc) (m) - NaN if not in mission or not geo based
	DistanceToTargetM float32
	// Trackline offtrack error (m) - NaN if not in mission or not in trackline
	CrossTrackErrorM float32
	// UUID of most recent mode change
	GcsSetModeUuid string `mavlen:"16"`
}

// GetID implements the message.Message interface.
func (*MessageMagothyMissionTelemetry) GetID() uint32 {
	return 50002
}
