//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Sent to/from Magothy Console and Vehicle. Used to transfer a portion of a loaded serialized mission payload. When the Vehicle receives this message, it will respond with MAGOTHY_MISSION_ACK
type MessageMagothyMissionTransfer struct {
	// system id of target system
	TargetSystem uint8
	// increment at the beginning of each "session", can be used to correlate different chunks or detect new sessions
	SessionId uint8
	// save uploaded mission to file mission{index}.yml. if value == 255, skip this step
	FilenameIndex uint8
	// chunk index
	ChunkIndex uint8
	// total number of chunks
	NumChunk uint8
	// CRC-16/CCITT-FALSE of complete payload
	Crc16 uint16
	// length of this chunk payload
	PayloadLen uint8
	// payload of this chunk
	Payload [247]uint8
}

// GetID implements the message.Message interface.
func (*MessageMagothyMissionTransfer) GetID() uint32 {
	return 50251
}
