//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Report 3D Magnetometer Calibration results, emitted after a successful calibration
type MessageMagothy_3dMagCalParams struct {
	// Hard Iron Offsets
	HardIron [3]float32
	// Soft Iron Rotation Matrix
	SoftIron [9]float32
	// Norm mean of raw mag data
	UncalibratedNormMean float32
	// Norm standard deviation of raw mag data
	UncalibratedNormStdDev float32
	// Maximum norm error (difference from 1.0) of raw mag data
	UncalibratedNormMaxError float32
	// Norm mean of calibrated mag data
	CalibratedNormMean float32
	// Norm standard deviation of calibrated mag data
	CalibratedNormStdDev float32
	// Maximum norm error (difference from 1.0) of calibrated mag data
	CalibratedNormMaxError float32
}

// GetID implements the message.Message interface.
func (*MessageMagothy_3dMagCalParams) GetID() uint32 {
	return 50101
}
