//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Sent from Magothy Console to Vehicle, requests a partial license manager file. Vehicle will respond with MAGOTHY_LICENSE_TRANSFER
type MessageMagothyLicenseTransferRequest struct {
	// system id of target system
	TargetSystem uint8
	// file type
	TransferType MAGOTHY_LICENSE_TRANSFER_TYPE `mavenum:"uint8"`
	// chunk index of license transfer
	ChunkIndex uint8
}

// GetID implements the message.Message interface.
func (*MessageMagothyLicenseTransferRequest) GetID() uint32 {
	return 50153
}
