//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Request to read the value of a parameter with either the param_id string id or param_index. PARAM_EXT_VALUE or PARAM_EXT_VALUE_TRIMMED should be emitted in response (see field: trimmed).
type MessageParamExtRequestRead struct {
	// System ID
	TargetSystem uint8
	// Component ID
	TargetComponent uint8
	// Parameter id, terminated by NULL if the length is less than 16 human-readable chars and WITHOUT null termination (NULL) byte if the length is exactly 16 chars - applications have to provide 16+1 bytes storage if the ID is stored as string
	ParamId string `mavlen:"16"`
	// Parameter index. Set to -1 to use the Parameter ID field as identifier (else param_id will be ignored)
	ParamIndex int16
	// Request _TRIMMED variants of PARAM_EXT_ messages. Set to 1 if _TRIMMED message variants are supported, and 0 otherwise. This signals the recipient that _TRIMMED messages are supported by the sender (and should be used if supported by the recipient).
	Trimmed uint8 `mavext:"true"`
}

// GetID implements the message.Message interface.
func (*MessageParamExtRequestRead) GetID() uint32 {
	return 320
}
