//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Reports speed and direction of water current
type MessageMagothyWaterCurrent struct {
	// Timestamp (UNIX Epoch time or time since system boot). The receiving end can infer timestamp format (since 1.1.1970 or since system boot) by checking for the magnitude of the number.
	TimeUsec uint64
	// Water Current Speed (m/s)
	WaterCurrentSpeedMps float32
	// Water Current Direction (deg)
	WaterCurrentDirectionDeg float32
	// Water Current Age (s)
	WaterCurrentAgeS float32
}

// GetID implements the message.Message interface.
func (*MessageMagothyWaterCurrent) GetID() uint32 {
	return 50003
}
