//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Send from Vehicle to Magothy Console. Sent as a response to MAGOTHY_LICENSE_TRANSFER_INITIALIZE and MAGOTHY_LICENSE_TRANSFER messages
type MessageMagothyLicenseTransferAck struct {
	// system id of target system
	TargetSystem uint8
	// file type
	TransferType MAGOTHY_LICENSE_TRANSFER_TYPE `mavenum:"uint8"`
	// chunk index
	ChunkIndex uint8
	// total number of chunks
	NumChunk uint8
	// CRC-16/CCITT-FALSE of complete payload
	Crc16 uint16
	// result of command
	Result MAV_RESULT `mavenum:"uint8"`
}

// GetID implements the message.Message interface.
func (*MessageMagothyLicenseTransferAck) GetID() uint32 {
	return 50155
}
