//autogenerated:yes
//nolint:revive,misspell,govet,lll
package magothy
// Teleop Safetey status message
type MessageMagothyTeleopSafety struct {
	// 1 if teleop safety is enabled, 0 if disabled
	IsEnabled uint8
	// 1 is teleop is currently safe, 0 if unsafe
	IsSafe uint8
	// 1 if teleop safety is latched unsafe, 0 if not latched
	IsSafeLatched uint8
	// Distance to nearest obstacle (m), NaN if no obstacle detected
	DistanceToObstacleM float32
	// Minimum distance to maintain from obstacles (m)
	MinSafeDistanceM float32 `mavext:"true"`
	// Field of view (deg)
	FieldOfViewDeg float32 `mavext:"true"`
	// Bearing to nearest obstacle (deg) clockwise from north, NaN if no obstacle detected
	BearingToObstacleDeg float32 `mavext:"true"`
}

// GetID implements the message.Message interface.
func (*MessageMagothyTeleopSafety) GetID() uint32 {
	return 50007
}
